# -*- mode: ruby -*-
# vi: set ft=ruby :

box_name = "win10-edge"

Vagrant.configure("2") do |config|
  config.vm.box = "modernIE/" + box_name
  config.vm.hostname = "#{`hostname`[0..-2]}".sub(/\..*$/,'') + box_name
  config.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"

  config.vm.network "forwarded_port", guest: 3389, host: 3389, id: "rdp", auto_correct: true
  config.vm.network "forwarded_port", guest: 4444, host: 4444, id: "selenium", auto_correct: true

  config.vm.communicator = "winrm"
  config.winrm.username = "IEUser"
  config.winrm.password = "Passw0rd!"

  config.vm.guest = :windows

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--vram", "128"]
    vb.customize ["modifyvm", :id,  "--cpus", "2"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000]
  end
end
